# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9367f5a00f61d0015a53098e7b5c2d916e3ec1d53f190a8c95faa804d232f902956c7c3fc9b603af10a83106635499b13fdd12e6fe33d088d448aba951fb7fb1

test:
  secret_key_base: 60e5a7187167464b740f2ee49dbeb87792aedb42dc5d9b4f3ed1cbfbf5a24cf3b0fc7e3d36a740b59c41efa0fac30ad4af830e92e226ab4eda82281d0998316d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
